export const SET_ALERT = 'SET_ALERT'
export const REMOVE_ALERT = 'REMOVE_ALERT'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAIL = 'REGISTER_FAIL'
export const USER_LOADED = 'USER_LOADED'
export const AUTH_ERROR = 'AUTH_ERROR'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAIL = 'LOGIN_FAILED'

export const LOG_OUT = 'LOG_OUT'

export const DELETE_ACCOUNT = 'DELETE_ACCOUNT'
export const CLEAR_PROFILE = 'CLEAR_PROFILE'

export const MEALS_INGREDIENTS_SUMMARY_UPDATE =
  'MEALS_INGREDIENTS_SUMMARY_UPDATE'
export const DAILY_INGREDIENTS_SUMMARY_UPDATE =
  'DAILY_INGREDIENTS_SUMMARY_UPDATE'
export const GAUGE_DATA_COUNT = 'GAUGE_DATA_COUNT'
export const DATE_CHANGE = 'DATE_CHANGE'
export const PAGE_TITLE_CHANGE = 'PAGE_TITLE_CHANGE'
export const SETTINGS_LOAD = 'SETTINGS_LOAD'

export const SET_USER_STATUS = 'set-user-status'
